server:
  port: 9081

spring:
  application:
    name: super-sesame
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost:5432}/supersesame
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    database: postgresql
    generate-ddl: true
    open-in-view: true

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    contexts: dev, faker
    enabled: true

jwt:
  secret: 46294A404D635166546A576E5A7234753778214125442A472D4B615064526755
  expiration: 86400000

application:
  role:
    default: ROLE_USER


logging:
  level:
    fr.insy2s: DEBUG
